// ESM entry, bundled by esbuild into web/src/generated/generator.js (a self-contained browser module).
// esbuild inlines builders-core.js + spec-builder.js + the JSON templates and resolves the CJS interop,
// so the frontend imports clean named exports. Regenerated by web's `npm run gen` (predev/prebuild hook).
export { specToParts } from './spec-builder.js';
export { assembleTop } from './builders-core.js';
