import { useEffect, useState } from 'react';
import { Moon, Sun, Save, FolderOpen, Trash2, RotateCcw } from 'lucide-react';
import INDEX from '../../registry/INDEX.json';
import { generateString } from './lib/generate';
import { useStore, activeSpec, initialSlug } from './store';
import {
  saveDraft,
  clearDraft,
  listSnapshots,
  saveSnapshot,
  deleteSnapshot,
  type Snapshot,
} from './lib/persistence';
import { Editor } from './components/Editor';
import { Button } from './components/ui/button';
import { Separator } from './components/ui/separator';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from './components/ui/select';
import { ToggleGroup, ToggleGroupItem } from './components/ui/toggle-group';

type Theme = 'light' | 'dark';

type ClassEntry = { slug: string; class: string; specs: string[] };
const CLASSES = (INDEX as { classes: ClassEntry[] }).classes;

export function App() {
  const [theme, setTheme] = useState<Theme>('dark');
  const [slug, setSlug] = useState(initialSlug);
  const [status, setStatus] = useState('');
  const [busy, setBusy] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [importText, setImportText] = useState('');
  const [saveAsOpen, setSaveAsOpen] = useState(false);
  const [saveName, setSaveName] = useState('');
  const [savedOpen, setSavedOpen] = useState(false);
  const [snaps, setSnaps] = useState<Snapshot[]>(() => listSnapshots());

  const storeSlug = useStore((st) => st.slug);
  const storeSpec = useStore((st) => st.spec);
  const setClass = useStore((st) => st.setClass);
  const switchClass = useStore((st) => st.switchClass);
  const forceReload = useStore((st) => st.forceReload);

  // Autosave the working SPEC as this class's per-class draft (debounced), so a reload reopens on it. Skip
  // sentinel slugs ('__boot__' / '__reload__') — those are transient states the Editor's load effect resolves.
  useEffect(() => {
    if (storeSlug.startsWith('__')) return;
    const t = setTimeout(() => saveDraft(storeSlug, storeSpec), 400);
    return () => clearTimeout(t);
  }, [storeSlug, storeSpec]);

  const flash = (msg: string) => { setStatus(msg); setTimeout(() => setStatus(''), 4000); };

  function pickClass(next: string) {
    setSlug(next);
    setStatus('');
  }

  // Save the current working WA as a named snapshot in localStorage.
  function doSaveAs() {
    const name = saveName.trim();
    if (!name) return;
    saveSnapshot(name, storeSlug, storeSpec);
    setSnaps(listSnapshots());
    setSaveAsOpen(false); setSaveName('');
    flash(`Saved "${name}"`);
  }
  // Load a snapshot: point the class dropdown at its class and commit its SPEC atomically (slug === storeSlug
  // afterwards, so the Editor's load effect won't reload the draft over it). It then becomes the class's draft.
  function doLoad(snap: Snapshot) {
    setSlug(snap.slug);
    switchClass(snap.slug, snap.spec);
    setSavedOpen(false);
    flash(`Loaded "${snap.name}"`);
  }
  function doDelete(id: string) {
    deleteSnapshot(id);
    setSnaps(listSnapshots());
  }
  // Discard this class's draft and reload its preset/default (the Editor rebuilds it — it has the registry).
  function doReset() {
    clearDraft(slug);
    forceReload();
    flash('Reset to preset');
  }
  function pickTheme(t: Theme) {
    if (!t) return; // ToggleGroup emits '' when deselecting the active item — ignore
    setTheme(t);
    document.documentElement.classList.toggle('dark', t === 'dark');
  }

  // Import a WA string (generated by this tool) back into the editor as the current SPEC. The backend
  // (/api/import) decodes it and decompiles it to a SPEC (lib/wa-to-spec.js); we load that into the store.
  async function importString() {
    setBusy(true); setStatus('');
    try {
      const res = await fetch('/api/import', {
        method: 'POST', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ string: importText.trim() }),
      });
      const data = await res.json();
      if (!data.ok) throw new Error(data.error || 'import failed');
      // The WA string carries no slug, but our generated SPEC ids start with the class name
      // ("Felsworn Tyrant SPEC"). Infer the class so the dropdown, icon resolution AND the per-class
      // autosave draft all match; fall back to the current class for an unrecognized (external) id.
      const inferred = CLASSES.find((c) => String(data.spec.id ?? '').toLowerCase().startsWith(c.class.toLowerCase()))?.slug;
      if (inferred) { setSlug(inferred); switchClass(inferred, data.spec); }
      else setClass(data.spec);
      setImportOpen(false); setImportText('');
      setStatus(inferred ? `Imported — ${data.regions} regions` : `Imported as ${slug} — class not detected`);
    } catch (e) {
      setStatus('Error: ' + (e instanceof Error ? e.message : String(e)));
    } finally {
      setBusy(false);
      setTimeout(() => setStatus(''), 4000);
    }
  }

  async function copyString() {
    setBusy(true); setStatus('');
    try {
      const str = await generateString(activeSpec(storeSpec));
      await navigator.clipboard.writeText(str);
      setStatus(`Copied — ${str.length} chars`);
    } catch (e) {
      setStatus('Error: ' + (e instanceof Error ? e.message : String(e)));
    } finally {
      setBusy(false);
      setTimeout(() => setStatus(''), 4000);
    }
  }

  return (
    <div className="grid h-screen grid-rows-[auto_1fr]">
      <header className="flex h-14 items-center gap-4 border-b bg-[image:var(--grad-bar)] px-4">
        <div className="flex items-center gap-2.5 font-semibold">
          <span className="grid size-7 place-items-center rounded-md bg-primary text-sm font-bold text-primary-foreground shadow-sm">
            W
          </span>
          <span className="tracking-tight">Forge</span>
          <span className="text-[11px] font-normal uppercase tracking-wider text-muted-foreground">
            CoA WeakAuras
          </span>
        </div>

        <Separator orientation="vertical" className="!h-6" />

        <Select value={slug} onValueChange={pickClass}>
          <SelectTrigger className="w-[168px]" aria-label="Class">
            <SelectValue placeholder="Class" />
          </SelectTrigger>
          <SelectContent>
            {CLASSES.map((c) => (
              <SelectItem key={c.slug} value={c.slug}>{c.class}</SelectItem>
            ))}
          </SelectContent>
        </Select>

        <div className="flex-1" />

        {status && (
          <span className="font-mono text-xs text-muted-foreground">{status}</span>
        )}

        <ToggleGroup
          type="single"
          value={theme}
          onValueChange={(v) => pickTheme(v as Theme)}
        >
          <ToggleGroupItem value="light" aria-label="Light">
            <Sun /> Light
          </ToggleGroupItem>
          <ToggleGroupItem value="dark" aria-label="Dark">
            <Moon /> Dark
          </ToggleGroupItem>
        </ToggleGroup>

        <Button variant="ghost" size="icon" aria-label="Reset to preset" title="Reset to preset" onClick={doReset}>
          <RotateCcw />
        </Button>

        <div className="relative">
          <Button variant="outline" onClick={() => { setSaveAsOpen((o) => !o); setSavedOpen(false); }}>
            <Save /> Save as
          </Button>
          {saveAsOpen && (
            <div className="absolute right-0 top-full z-50 mt-2 w-[280px] rounded-md border bg-card p-3 shadow-lg">
              <label className="mb-1.5 block text-xs text-muted-foreground">Snapshot name</label>
              <input
                autoFocus
                value={saveName}
                onChange={(e) => setSaveName(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter') doSaveAs(); }}
                placeholder="My Felsworn v2"
                className="w-full rounded-md border bg-background px-2 py-1.5 text-sm outline-none focus:ring-2 focus:ring-ring"
              />
              <div className="mt-2 flex justify-end gap-2">
                <Button variant="ghost" onClick={() => { setSaveAsOpen(false); setSaveName(''); }}>Cancel</Button>
                <Button onClick={doSaveAs} disabled={!saveName.trim()}>Save</Button>
              </div>
            </div>
          )}
        </div>

        <div className="relative">
          <Button variant="outline" onClick={() => { setSavedOpen((o) => !o); setSaveAsOpen(false); }}>
            <FolderOpen /> Saved
          </Button>
          {savedOpen && (
            <div className="absolute right-0 top-full z-50 mt-2 w-[300px] rounded-md border bg-card p-1.5 shadow-lg">
              {snaps.length === 0 ? (
                <div className="px-2 py-3 text-center text-xs text-muted-foreground">No saved snapshots</div>
              ) : (
                snaps.map((s) => (
                  <div key={s.id} className="flex items-center gap-2 rounded-md px-2 py-1.5 hover:bg-accent">
                    <button className="min-w-0 flex-1 text-left" onClick={() => doLoad(s)}>
                      <div className="truncate text-sm">{s.name}</div>
                      <div className="truncate text-[11px] text-muted-foreground">
                        {CLASSES.find((c) => c.slug === s.slug)?.class ?? s.slug} · {new Date(s.createdAt).toLocaleDateString()}
                      </div>
                    </button>
                    <button
                      className="shrink-0 rounded p-1 text-muted-foreground hover:text-destructive"
                      aria-label={`Delete ${s.name}`}
                      onClick={() => doDelete(s.id)}
                    >
                      <Trash2 className="size-4" />
                    </button>
                  </div>
                ))
              )}
            </div>
          )}
        </div>

        <div className="relative">
          <Button variant="outline" onClick={() => { setImportOpen((o) => !o); setSaveAsOpen(false); setSavedOpen(false); }}>
            Import string
          </Button>
          {importOpen && (
            <div className="absolute right-0 top-full z-50 mt-2 w-[420px] rounded-md border bg-card p-3 shadow-lg">
              <label className="mb-1.5 block text-xs text-muted-foreground">
                Paste a WeakAuras string generated by Forge
              </label>
              <textarea
                autoFocus
                value={importText}
                onChange={(e) => setImportText(e.target.value)}
                placeholder="!WA:2!..."
                spellCheck={false}
                className="h-24 w-full resize-none rounded-md border bg-background px-2 py-1.5 font-mono text-xs outline-none focus:ring-2 focus:ring-ring"
              />
              <div className="mt-2 flex justify-end gap-2">
                <Button variant="ghost" onClick={() => { setImportOpen(false); setImportText(''); }}>
                  Cancel
                </Button>
                <Button onClick={importString} disabled={busy || !importText.trim().startsWith('!WA:2!')}>
                  {busy ? 'Importing…' : 'Load'}
                </Button>
              </div>
            </div>
          )}
        </div>

        <Button onClick={copyString} disabled={busy}>
          {busy ? 'Generating…' : 'Copy import string'}
        </Button>
      </header>

      <Editor slug={slug} />
    </div>
  );
}
