// Coverage report — a living map of what's packaged vs what remains, across all 21 CoA classes.
//
// The scrape covers all 21 classes (registry/*.json), but a *package* exists only where a classes/<slug>/
// spec.json is wired — and only for ONE spec per class so far. This crosses the registry (classes + their
// specs), the wired spec.json files, and resource-model.json (is the primary power index confirmed, without
// which a powerBar would be a guess) into tools/COVERAGE.md, so scaling is a data-entry task with a clear
// queue instead of a vibe.
//
// Usage:  node tools/coverage-report.js      (writes tools/COVERAGE.md + prints a one-line summary)
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const INDEX = JSON.parse(fs.readFileSync(path.join(ROOT, 'registry', 'INDEX.json'), 'utf8')).classes;
const RES = JSON.parse(fs.readFileSync(path.join(ROOT, 'registry', 'resource-model.json'), 'utf8'));

// which class+spec are wired: read each classes/<slug>/spec.json, note its slug (+ infer the spec from id/name)
const CLASSES_DIR = path.join(ROOT, 'classes');
const wired = {}; // slug -> [specName...]
for (const d of fs.readdirSync(CLASSES_DIR)) {
  const p = path.join(CLASSES_DIR, d, 'spec.json');
  if (!fs.existsSync(p)) continue;
  const spec = JSON.parse(fs.readFileSync(p, 'utf8'));
  const slug = spec.slug || d;
  // the spec's human name is embedded in `id` (e.g. "Felsworn Tyrant SPEC"); match it against the class's specs
  const entry = INDEX.find(c => c.slug === slug);
  let specName = null;
  if (entry) specName = entry.specs.find(s => (spec.id || '').includes(s)) || null;
  (wired[slug] ||= []).push(specName || spec.id || d);
}

let totalSpecs = 0, doneSpecs = 0;
const lines = [];
lines.push('# Coverage — CoA class packages');
lines.push('');
lines.push('> Auto-generated by `node tools/coverage-report.js`. Re-run after wiring a new spec.');
lines.push('');
lines.push('`res` = primary resource power index: **confirmed** (safe to emit a powerBar) or *inferred* (index');
lines.push('unknown — a powerBar would be a guess; confirm in-game before adding one, or track it as an aura-stack).');
lines.push('');
lines.push('| Class | Specs (✅ = packaged) | Abilities | Resource | res index |');
lines.push('|---|---|---|---|---|');

for (const c of INDEX) {
  const done = wired[c.slug] || [];
  const specCells = c.specs.map(s => done.includes(s) ? `✅ ${s}` : s).join(', ');
  totalSpecs += c.specs.length;
  doneSpecs += c.specs.filter(s => done.includes(s)).length;
  const r = RES[c.slug];
  const resName = r && r.primary ? r.primary.name : '?';
  const resIdx = r && r.confirmed && r.primary && r.primary.index != null
    ? `**${r.primary.index}** ✅` : (r && r.primary && r.primary.index != null ? String(r.primary.index) : '— *infer*');
  const points = r && r.points && r.points.length ? ` (+${r.points.map(p => p.name).join('/')})` : '';
  lines.push(`| ${c.class} | ${specCells} | ${c.abilityCount} | ${resName}${points} | ${resIdx} |`);
}

// a wired class whose spec.json id names no known spec (e.g. cultist "Cultist SPEC") is packaged but
// unattributable — surface it instead of silently under-counting.
const unlabeled = Object.entries(wired)
  .filter(([slug, specs]) => { const e = INDEX.find(c => c.slug === slug); return e && !specs.some(s => e.specs.includes(s)); })
  .map(([slug]) => INDEX.find(c => c.slug === slug).class);

lines.push('');
lines.push(`**${doneSpecs} / ${totalSpecs} named class-specs packaged** (${INDEX.length} classes, ${Object.keys(wired).length} touched).`);
if (unlabeled.length) {
  lines.push('');
  lines.push(`> ⚠ Packaged but spec-unlabeled (id names no known spec — pick a spec name in its \`spec.json\` \`id\`, ` +
    `but note that changing the id shifts uids so re-imports create a new set): **${unlabeled.join(', ')}**.`);
}
lines.push('');
lines.push('## Next-up queue');
lines.push('');
lines.push('Fastest wins first: **remaining specs of classes already wired** (resource model + layout known) beat');
lines.push('brand-new classes. Ordered by that heuristic:');
lines.push('');
const touched = new Set(Object.keys(wired));
const secondSpecs = [], newClasses = [];
for (const c of INDEX) {
  const done = wired[c.slug] || [];
  const remaining = c.specs.filter(s => !done.includes(s));
  if (!remaining.length) continue;
  const r = RES[c.slug];
  const confirmed = r && r.confirmed;
  const tag = confirmed ? 'res ✅' : 'res needs confirm';
  const item = `- **${c.class}** — ${remaining.join(', ')}  _(${tag})_`;
  (touched.has(c.slug) ? secondSpecs : newClasses).push(item);
}
lines.push('### More specs of already-wired classes');
lines.push(...(secondSpecs.length ? secondSpecs : ['- _(none — every wired class has only the one spec done)_']));
lines.push('');
lines.push('### New classes (0 packages yet)');
lines.push(...newClasses);
lines.push('');

fs.writeFileSync(path.join(ROOT, 'tools', 'COVERAGE.md'), lines.join('\n'));
console.log(`Wrote tools/COVERAGE.md — ${doneSpecs}/${totalSpecs} class-specs packaged across ${INDEX.length} classes`);
