// WA-Forge agent backend — Hono.
//
// One Node server (later serves the SPA build too). Routes:
//   node server/server.mjs                # listens on $PORT (default 8374)
//   GET  /health                          # -> { ok: true }
//   POST /api/agent   { spec }            # -> { ok, regions, name }  |  { ok:false, error }  (400)
//   POST /api/agent   { spec, messages, slug }
//                                         # -> NDJSON stream ({type:model|text|tool|done|reset|error}\n ...)
//
// Hono (web-standard Request/Response) over @hono/node-server. The agent lives in agent.mjs (ESM); the
// isomorphic validator (lib/spec-builder.js) is CJS, pulled in via createRequire.
import { Hono } from 'hono';
import { serve } from '@hono/node-server';
import { serveStatic } from '@hono/node-server/serve-static';
import { stream } from 'hono/streaming';
import { bodyLimit } from 'hono/body-limit';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { specToParts } = require('../lib/spec-builder.js');
const { decodeWA } = require('../lib/wa-codec.js');
const { waToSpec } = require('../lib/wa-to-spec.js');

const PORT = Number(process.env.PORT) || 8374;
const MAX_BODY = 1 << 20;   // 1 MB — a SPEC is small JSON; reject anything absurd.

// Validate a SPEC exactly as the generator would. Throws are turned into a structured error by the caller.
function validate(spec) {
  const { name, children } = specToParts(spec);   // throws loudly on any invalid element/field/dup id
  return { ok: true, name, regions: children.length };
}

const app = new Hono();

app.get('/health', (c) => c.json({ ok: true }));

// Decompile a WA import string (generated by THIS tool) back into an editable SPEC. Decode -> waToSpec ->
// validate (so we only hand back a SPEC the generator accepts). External / non-Forge strings that don't
// match the shapes we emit fail loudly rather than yielding a wrong SPEC.
//   POST /api/import { string }  -> { ok, spec, name, regions } | { ok:false, error } (400)
app.post(
  '/api/import',
  bodyLimit({ maxSize: MAX_BODY, onError: (c) => c.json({ ok: false, error: 'body too large' }, 413) }),
  async (c) => {
    let body;
    try { body = await c.req.json(); }
    catch { return c.json({ ok: false, error: 'invalid JSON body' }, 400); }
    const str = body && typeof body.string === 'string' ? body.string.trim() : '';
    if (!str.startsWith('!WA:2!')) return c.json({ ok: false, error: 'not a !WA:2! import string' }, 400);
    try {
      const spec = waToSpec(decodeWA(str).data);
      const { name, children } = specToParts(spec);   // validate the reconstructed SPEC
      return c.json({ ok: true, spec, name, regions: children.length });
    } catch (e) {
      return c.json({ ok: false, error: String(e.message || e) }, 400);
    }
  },
);

app.post(
  '/api/agent',
  bodyLimit({ maxSize: MAX_BODY, onError: (c) => c.json({ ok: false, error: 'body too large' }, 413) }),
  async (c) => {
    let body;
    try { body = await c.req.json(); }
    catch { return c.json({ ok: false, error: 'invalid JSON body' }, 400); }
    if (!body || typeof body.spec !== 'object' || body.spec === null)
      return c.json({ ok: false, error: 'body needs a `spec` object' }, 400);

    // No messages -> pure validation round-trip. With messages -> run the agent.
    if (!Array.isArray(body.messages) || body.messages.length === 0) {
      try { return c.json(validate(body.spec)); }
      catch (e) { return c.json({ ok: false, error: String(e.message || e) }, 400); }
    }
    if (!process.env.OPENROUTER_API_KEY)
      return c.json({ ok: false, error: 'OPENROUTER_API_KEY not set' }, 503);
    if (typeof body.slug !== 'string')
      return c.json({ ok: false, error: 'agent requests need a `slug`' }, 400);

    // Stream the run as NDJSON: one JSON event per line, flushed as it happens so the frontend can show the
    // answer + tool trace scrolling live.
    const { runAgentStream } = await import('./agent.mjs');
    c.header('content-type', 'application/x-ndjson');
    c.header('cache-control', 'no-cache');
    c.header('x-accel-buffering', 'no');
    return stream(c, async (s) => {
      try {
        for await (const ev of runAgentStream({ slug: body.slug, spec: body.spec, messages: body.messages }))
          await s.write(JSON.stringify(ev) + '\n');
      } catch (e) {
        await s.write(JSON.stringify({ type: 'error', error: String(e.message || e) }) + '\n');
      }
    });
  },
);

// In production (fly.io) the same Node process also serves the built SPA (web/dist), so the frontend
// calls /api/* same-origin — set STATIC_DIR=./web/dist. Registered AFTER the API routes: real asset
// files are served as-is; any other GET falls back to index.html (client-side routing). Unset in dev,
// where Vite serves the SPA and proxies /api to this server.
const STATIC_DIR = process.env.STATIC_DIR;
if (STATIC_DIR) {
  app.use('/*', serveStatic({ root: STATIC_DIR }));
  app.get('*', serveStatic({ path: './index.html', root: STATIC_DIR }));
}

app.notFound((c) => c.json({ ok: false, error: 'not found' }, 404));

serve({ fetch: app.fetch, port: PORT }, () => console.log(`wa-forge agent (hono) listening on :${PORT}`));
